### PR TITLE
Half-dome integrated

### PR DESCRIPTION
**Pull request by Zkir**
Half-dome integrated. So many files changed, because the original code duplicates a lot.

### CODE REVIEW

**Comment by vvoovv** [comment]
A quick review:

* Remove _test.bat_ from the repo
* Don't touch the old code (_building/renderer.py_, _realistic/building/renderer.py_, _setup/example_custom_textures.py_, _setup/neoclassical.py_, _setup/premium_default.py_)
* style/default.py isn't used anymore. PML files should used now. Pull the latest _dev_ branch.
* I don't like patching _RoofGeneratrix_ item renderer:
```python
def __init__(self, generatrix, exportMaterials=False, halfDome=False):
```
Please create a new item renderer for the half dome and derive it from the _RoofGeneratrix_ item renderer.

**Comment by vvoovv** [comment]
Also util/polygon.py has the property _maxEdgeIndex_. Use it instead of _MidleOfLongestSide_.

**Comment by Zkir** [comment]
>Remove test.bat from the repo

Ok, sure. My fault. I've fixed that. 

>Don't touch the old code

I do not really know what code is old or new (and do not really want to). Since code is still in the repo\branch, I think it should be patched. I guess you can remove any unused files later.  Also feel free to merge only what you think appropriate. 

>I don't like patching RoofGeneratrix item renderer:

But it's correct. To generate geometric shape using the generatrix approach, you really need three things:
* Outline
* Generatix  profile
* Base point.

Base point could be the outline center, or it could be the middle of the longest edge, or even an arbitrary point. 

Maybe we could name a parameter and values in are more nice way, something like:

`def __init__(self, generatrix, basePoint='Center', exportMaterials=False ):`

Maybe enum should be used, I do not know python too well. 
BasePoint=enum('Center','MiddleOfTheLongesSide')

I do not see why to create a new class, which have absolutely no new functionality or new structure, just a new parameter. 

Also i do not understand how this inheritance could be done. Copy-paste renderSharpSideEdges()  and renderIgnoreEdges() to a new file?

>util/polygon.py has the property maxEdgeIndex. Use it instead of MidleOfLongestSide.

Not quite get how to do it exactly. MidleOfLongestSide() is a function which returns coordinates (Vector()), however,maxEdgeIndex is just an index. Also, with what array this index should be used? Is there any set of edges?

**Comment by vvoovv** [comment]
How to use _polygon.maxEdgeIndex_ instead of _MidleOfLongestSide_:

```python
        polygon = footprint.polygon
        verts = polygon.allVerts
        indices = polygon.indices
        maxEdgeIndex = polygon.maxEdgeIndex
        middle = ( verts[indices[maxEdgeIndex+1]] - verts[indices[maxEdgeIndex]] )/2.
```

**Comment by vvoovv** [comment]
I'll check if it's possible to merge selected files only rather than all.

**Comment by vvoovv** [comment]
Let's create two constants in the module _item_renderer.texture.roof_generatrix_:
```python
Center = 1
MiddleOfTheLongesSide = 2
```
And import them in the line [15](https://github.com/vvoovv/blender-osm/blob/dev/setup/realistic_dev.py#L15)

**Comment by vvoovv** [comment]
> I'll check if it's possible to merge selected files only rather than all.

It seems to be not an easy task.
Please use the version from HEAD for the files:
* building/renderer.py
* realistic/building/renderer.py
* setup/example_custom_textures.py
* setup/neoclassical.py
* setup/premium_default.py

**Comment by Zkir** [comment]
Ok, here is the new version.

1.  I've rollback the 'old' files (I still suggest removing the unnecessary code).
2. Constants have been introduced
3. Name of the function middleOfTheLongestSide() spelled properly.
It should be a function, because it is called **twice** in roof_generatrix file. 
It's counterpart for centerBB(), and I guess the best place for both is polygon.py

```
        polygon = footprint.polygon
        verts = polygon.allVerts
        indices = polygon.indices
        maxEdgeIndex = polygon.maxEdgeIndex
        middle = ( verts[indices[maxEdgeIndex+1]] - verts[indices[maxEdgeIndex]] )/2.
```
This does not work, center is placed in the wrong (and very strange) place. 
I think you can improve implementation of this function later, if needed.

**Comment by vvoovv** [comment]
Thank  you! I'll integrate it in a few days

**Comment by Zkir** [comment]
Thank you very much too!

And to make you even more happy, implementation of middleOfTheLongestSide() has been improved by myself.

It should read:
middle = ( verts[indices[maxEdgeIndex+1]] **+** verts[indices[maxEdgeIndex]] )/2.
not 
middle = ( verts[indices[maxEdgeIndex+1]] **-** verts[indices[maxEdgeIndex]] )/2.

**Comment by vvoovv** [comment]
> It should read:
> middle = ( verts[indices[maxEdgeIndex+1]] **+** verts[indices[maxEdgeIndex]] )/2.
> not
> middle = ( verts[indices[maxEdgeIndex+1]] **-** verts[indices[maxEdgeIndex]] )/2.

Exactly! My bad!

I'll merge it in a few days.

Could you please attach an OSM file for testing in the comment?

**Comment by Zkir** [comment]
Osm file for testing, as requested

[half-dome.zip](https://github.com/vvoovv/blender-osm/files/4805859/half-dome.zip)

**Pull request merged**
