### PR TITLE
Vertices reduction proposal

### PR DESCRIPTION
**Pull request by al1brn**
Based on the issue I wrote, here is the code I propose.

To reduce the number of vertices, I simply take one vertex on n. This gives a 1/n reduction ratio per dimension. The resulting reduction ratio is 1/n².

The value n must be a true divider of 1,200 which gives a lot of possibilities. I implemented : 1, 2, 5, 10, 20, 50, 100, 200, 400, 600 and 1,200.

With these values, the first reduction ratio is 25% up to 0,0028%.

The resulting number of vertices is displayed to help selecting the best reduction ratio.

The algorithm could be improved by computing average height with the ignored points.

Not sure this is necessary since reducing the number of vertices comes with loosing resolution.

BR

### CODE REVIEW

**Comment by vvoovv** [comment]
Thank you! I'll review it this week.

**Comment by vvoovv** [comment]
I am not familiar with the notation _1%%_ (double %). So I guess it's also unknown for some users.

**Comment by al1brn** [comment]
It is a notation I created. I thought it was clearer than ‱ which is the good symbol but people are not necessarily familiar with. No problem to replace 1%% by 1‱ or by 0.01%.

**Comment by vvoovv** [comment]
I'd prefer to have 0.01% that everyone knows.

**Comment by al1brn** [comment]
I've made the change. Not sure if I have to create a new pull request to submit it.

**Comment by vvoovv** [comment]
Great! Thanks.
I'll integrate it in the coming days.

**Comment by vvoovv** [comment]
Hi @al1brn 
You code is in the repo and on Gumroad. I ended up copying and pasting your code. That's due to a large number of whitespace changes.

Thank you very much for your contribution!

**Pull request closed without merging**
