### PR TITLE
Fix Issue #13

### PR DESCRIPTION
**Pull request by esistderfred**
use building:levels if no height data is set

### CODE REVIEW

**Comment by vvoovv** [comment]
Please read the text in the lines 1-4 of the file [io_import_scene_osm.py](https://github.com/vvoovv/blender-geo/blob/master/io_import_scene_osm.py)
Please resubmit your changes in accordance with the instruction

**Comment by esistderfred** [comment]
Sorry!

Done.

**Comment by vvoovv** [comment]
I have only one note.

You set heightPerLevel twice in the code. I suggest to make it a global variable in the module osm_import_handlers.py

**Comment by vvoovv** [comment]
Support for building:levels and building:min_level is implemented in a bit different way in https://github.com/vvoovv/blender-geo/commit/41b1cc33514812de47310112ab3c87b9c6dc0f54
Thank you for your contribution!

**Pull request closed without merging**
