### PR TITLE
Added building parts, naturals and some initial materials

### PR DESCRIPTION
**Pull request by gtoonstra**
Resubmitting. I'm obviously still working on the materials part, so it's still wip, but this allows us to get synchronized.

### CODE REVIEW

**Comment by vvoovv** [comment]
I'd suggest to have default=False for importNaturals. Not everyone wants to have objects tagged with "natural".

Materials are tricky. Some want materials for Cycles, the others want materials for Blender Internal (e.g. for export). A solution could to have a mapping table <material type> -> <Blender material>.  A user could redefine some or all entries in the mapping table.

**Comment by vvoovv** [comment]
What about [building:levels](http://wiki.openstreetmap.org/wiki/Key:building:levels) tag? Many buildings have that tag.

**Comment by gtoonstra** [comment]
default=False is ok for naturals. Maybe only buildings are to be imported by default with all the rest as optional.
I saw building:levels, but my map doesn't have those. 
It's a great opportunity to add additional vertices per story so that one only has to create material for a single story. That way, the textures don't look stretched. The buildings can further be classified by other parameters (is there an "office" tag?), or by building width, to account for medium income building types versus very rich residential appartments, so that materials of different types can be attributed to different buildings having the same levels tag, but they happen to be in different areas or have different attributes mapped to them.

**Comment by vvoovv** [comment]
I personally do mapping in OSM and always apply building:levels, since it's easy to calculate the number of levels, but there is no way to measure the height of a building.
Also, [Simple 3D Buildings](http://wiki.openstreetmap.org/wiki/Simple_3D_Buildings) specification has  `building:levels` and `building:min_level` tags along with `heigth` and `min_height` tags
It seems that `height` and `min_height` have a preference against `building:levels` and `building:min_level`

**Comment by gtoonstra** [comment]
I think the height of buildings in OSM is just an estimate. Even with the number of levels, you'd have to define the height for each level. If a city has a map of terrain elevation and a regular elevation map showing the elevations measured from space (including houses), it would be possible to establish a similarly accurate height estimate. 

I think that's what this guy did here: https://www.youtube.com/watch?v=ATTJZ8eK-fA

**Comment by vvoovv** [comment]
So would you like to support `building:levels` and `building:min_level`?

**Comment by gtoonstra** [comment]
Sure. I have some other tasks today, but will get to this soon as I can. All we need is to agree on the actual height in meters of a single level, because there has to be some conversion somewhere. We can add this as a sensible parameter too. 

Can you create an issue in your project to achieve this, so we can track progress?

**Comment by gtoonstra** [comment]
ah, just noticed. already there. Can we close this pull request ?

**Pull request merged**
