### PR TITLE
Fix for import as single mesh.

### PR DESCRIPTION
**Pull request by gtoonstra**
Should fix issue #11 . Also does not import naturals or building parts when importing as single mesh, because this creates issues with planes drifting around in space.

### CODE REVIEW

**Comment by vvoovv** [comment]
I didn't get why you skipped building part in the single mesh mode. Building parts would be a useful feature also in the single mesh mode

**Comment by gtoonstra** [comment]
I agree, but there's an issue there. When no thickness is used, you have some planes hanging in mid air that are not extruded. When thickness is used, then since this is a single mesh, the mesh is extruded to the height of thickness. This is because the mesh is built as a set of planes first, then extruded in its entirety.

For the same reason, the naturals are not included, because they get extruded to the same level of the buildings.

**Comment by vvoovv** [comment]
I'd like building parts imported in the single mesh mode. There is no way to import a whole city if every building is imported as a separate object. Naturals and highways should be never extruded.

**Comment by gtoonstra** [comment]
Is there a limit to the number of objects that may be imported into blender, or does it simply consume a lot more memory? There's some thinking to do here and I'd like your input on the approach. 

1. The way this works is that the code first establishes a blue print of vertices, which are then extruded by the thickness parameter. If building parts are to be part of the single mesh too, then they'd be extruded by the same thickness, distorting their appearance. They have their own height parameter set in the data and this is pretty much guaranteed for that kind of data. It's already clear that if highways and naturals are part of the same mesh, they'd be extruded similarly.

2. Another issue is that with separate models, you can decide the height of each building. In single mesh mode, building:level and height tags cannot be used, because it's impossible to apply them to one single building in a single mesh, so only thickness is applied as a global parameter. This makes it unlikely that building parts connect to their building base, so they appear to float around in space or appear shorter than they are.

a. One way to solve that is to create 4 separate meshes: 
- one for the buildings that are extruded to the 'thickness' parameter
- one for all building parts using their respective height parameters in the data to make them appear correct, although the bottom level may appear to float in space or sink too deep into the base building.
- one for highways
- one for naturals
- extrude only the buildings mesh

b. Another way is to continue what's being done now, which is to ignore naturals and building parts in single mesh mode.

c. As a variant on a, use thickness to recalculate the bottom level for the building parts, so that all heights are readjusted, so that they no longer float in space.

**Comment by vvoovv** [comment]
Try to import a whole city (Karlsruhe in Germany) in the mode "each building as a separate object" before you go for lunch:
https://www.dropbox.com/s/t2so5kkcr2kkkdg/karlsruhe.zip?dl=0

Then try the same in the single mesh mode.

**Comment by vvoovv** [comment]
Regarding behavior in the single mesh mode:

Highways and naturals could be imported in a separate mesh and should be never extruded. A user may extuded them manually be selecting the related object and extruding it

Concerning buildings. I'd suggest to have an option "Import only building outlines" (i.e. import buildings and building parts as flat structures). That applies to both the "single mesh" and "each building as a separate object" modes. If 3D look is desired (i.e. "Import only building outlines" is unchecked), utils.extrudeMesh is applied only to those buildings that don't have height information in any way.

If there are buildings floating in the air, I suggest to do nothing. Maybe the building stays on a hill.

**Comment by vvoovv** [comment]
I've found a type in your code. The correct tag is `min_height` (not `building:min_height`, i.e. without `building:` prefix). I fixed the typo in the master branch.

I understand why buildings are hanging in the air. The problem is that we don't process relations. Some building:parts are mapped via relations. Relations may refer to ways and nodes.

**Comment by vvoovv** [comment]
An example of `building:part` mapped with relation: http://www.openstreetmap.org/relation/3440931

**Comment by gtoonstra** [comment]
I became side-tracked with other issues, but I did do the import and it did take 3 hours, so that's not feasible in many cases. At the same time, scenery that large probably requires different technology with dynamic loading to make it feasible.

So the building parts are for example church towers, they're not on a hill. I'm thinking that they should probably only be included when this new option "import outlines"  is checked?  

I have data here that does use the building: prefix, so probably that's osm code not being consistent. We can check for both.

Not sure about the relations processing, that needs to be investigated. Does that mean a relation can transfer properties from one object to another?

**Comment by vvoovv** [comment]
Did you try it with the "single mesh" mode? For it takes a few minutes in the "single mesh" mode.

Could you send a link to the example with the church that is hanging in the air?

How many occurances of `building:min_height` do you have in your data? If not that many, all those occurances can be replaced with `min_height` in the OSM database.

In the preliminary pass we create dictionaries for nodes and for ways. An entry in the dictionary for ways contains references to the related nodes. In the similar manner a dictionary for relations should be created. Each entry in the dictionary for relations should contain references to the related ways and nodes.

Each relations can have tags. The best way to tag a building with inner yard is via a relation. In that case the relation references two ways: one for the external building outline and the other one for the inner yard. The tags are set for the relation, not for ways. In the same ways naturals with holes are mapped. I don't know if a polygon with a hole can be created in bmesh.

**Comment by vvoovv** [comment]
#11 was fixed in https://github.com/vvoovv/blender-geo/commit/2b58c0d73671d0825dcf8c65639422ede2c82ab2

**Comment by vvoovv** [comment]
Still, thank you for your contributions!

**Pull request closed without merging**
